version: 2.1

jobs:
  test_black:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
    working_directory: ~/dash-sample-apps

    steps:
      - checkout
      - run:
          name: install black
          command: |
            sudo pip install black==19.10b0
      - run:
          name: run black
          command: |
            black . --check

  deploy:
    docker:
      - image: cimg/base:stable-20.04
    working_directory: ~/dash-sample-apps
    parameters:
      only_changed_apps:
        type: boolean
    steps:
      - checkout
      - dash_git_setup
      - install_dds_client
      - dash_deploy:
          only_changed_apps: << parameters.only_changed_apps >>


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test_black

      #
      #
      # Feature branch deploys
      - deploy:
          name: Deploy to dash-playground
          context: dash-playground-credentials
          requires:
            - test_black
          filters:
            branches:
              ignore:
              - main
          only_changed_apps: true
      
      - deploy:
          name: Deploy to dash-playground-k8s
          context: dash-playground-k8s-credentials
          requires:
            - test_black
          filters:
            branches:
              ignore:
              - main
          only_changed_apps: true

      #
      #
      # main branch deploys
      - deploy:
          name: Deploy to dash-gallery
          context: dash-gallery-credentials
          requires:
            - test_black
          filters:
            branches:
              only:
              - main
          only_changed_apps: false

commands:
  dash_git_setup:
    steps:
    - run:
        name: Create helper-script
        command: printf '#!/bin/bash\necho username=$DASH_ENTERPRISE_USERNAME\necho password=$DASH_ENTERPRISE_PASSWORD' >> /home/circleci/helper-script.sh
    - run:
        name: Set up git config
        command: |
          git config --global credential.helper "/bin/bash /home/circleci/helper-script.sh"
          git config --global user.email '<>' # Leave email blank
          git config --global user.name "Circle MonoRepo Automatic Deployer"
          git config --global protocol.version 0

  install_dds_client:
    steps:
    - run:
        name: Install dds-client
        command: |
          curl -sSL -o dds-client.tgz https://github.com/plotly/dds-client/releases/download/v0.3.0/dds-client_0.3.0_linux_x86_64.tgz
          mkdir $HOME/bin
          tar xzf dds-client.tgz -C $HOME/bin
          chmod +x $HOME/bin/dds-client

  dash_deploy:
    parameters:
      only_changed_apps:
        type: boolean
    steps:
    - run:
        name: Deploy
        environment:
          CREATE_APP: "true"
          CREATE_DBS: "false"
        command: |
          APPS_MODIFIED=$(ls apps | sort -u)
          <<# parameters.only_changed_apps >>
          APPS_MODIFIED=$(git diff origin/main origin/$CIRCLE_BRANCH --dirstat=files,1 apps/ | awk '{ split($2,a,"/"); if (length(a[2]) != 0) { print a[2]} } ' | sort -u)
          <</ parameters.only_changed_apps >>

          if [ -z "$APPS_MODIFIED" ]
          then
            echo "No app change detected. Skipping the deploy.."
            exit 0
          fi

          for APP in $APPS_MODIFIED
          do
            PATH="$HOME/bin:$PATH" ./deploy "$APP"
          done